Add a TOC vacancies policy
cdfoundation/toc pull request #204
Opened 2023-05-23 14:49 UTC by afrittoli

Add a TOC policy to define what happens in case of temporary or permanent leave from the TOC of one of its members.

2023-05-23 15:19 UTC, sbtaylor15 approved these changes
/lgtm

2023-05-24 12:31 UTC, McGon-Fid requested changes
In vacanies.md on line 5 if we can include a link to the TOC email list. Thanks.

2023-05-24 16:31 UTC, afrittoli commented on process/vacancies.md
> +These policy cover the cases of TOC members changing affiliation and temporarily or permanently leaving the TOC. For any case that cannot be resolved through this policy, the CDF Governing Board may
@sbtaylor15 I added this to address your comment, wdyt?

2023-05-24 16:32 UTC, afrittoli commented
> In vacanies.md on line 5 if we can include a link to the TOC email list. Thanks.

Done, thank you!

2023-05-31 15:47 UTC, McGon-Fid approved these changes
LGTM @afrittoli Thanks

2023-05-31 16:50 UTC, merged