Propose Events SIG
cdfoundation/toc pull request #91
Opened 2021-01-28 18:34 UTC by e-backmark-ericsson

This is a proposal for the Events in CI/CD workstream to become a SIG

2021-01-28 21:06 UTC, dlorenc commented
Thanks!

2021-01-29 09:51 UTC, afrittoli commented
Nice work, thank you!

2021-01-29 15:23 UTC, m-linner-ericsson requested changes
I guess we want the same cadence as the [Interoperability SIG](https://calendar.google.com/calendar/u/0/r/week/2021/2/4?eid=MWhtcXNkcHMzMDRvcXZoazg0azV0b2F1NGhfMjAyMTAyMDRUMTYwMDAwWiBsaW51eGZvdW5kYXRpb24ub3JnX21oZjBrbWdlZG42N2lobmk4cjEyOWF2cDI0QGc&ctz=Europe/Stockholm&sf=true)

2021-01-29 15:23 UTC, m-linner-ericsson commented on sigs/sig-events.md
> +The SIG meets every second Monday, at 4 PM CET. Meeting notes can be seen [here](https://github.com/cdfoundation/sig-interoperability/blob/master/workstreams/events_in_cicd/meetings.md)
```suggestion
The SIG meets on the 1st and 3rd Monday, at 4 PM CET. Meeting notes can be seen [here](https://github.com/cdfoundation/sig-interoperability/blob/master/workstreams/events_in_cicd/meetings.md)
```

2021-02-01 12:26 UTC, ravilach reviewed
Excited for the new sig!

2021-02-01 12:48 UTC, m-linner-ericsson approved these changes

2021-02-01 13:14 UTC, afrittoli commented
NIT: we might update the list in https://github.com/cdfoundation/toc/tree/master/sigs/README.md as well, but it would be ok to do so in a follow-up PR too.

2021-02-01 13:26 UTC, e-backmark-ericsson commented
> NIT: we might update the list in https://github.com/cdfoundation/toc/tree/master/sigs/README.md as well, but it would be ok to do so in a follow-up PR too.

@afrittoli , the README is already in this PR :)

2021-02-02 16:16 UTC, e-backmark-ericsson commented
Current info on the events workstream in the Interop SIG: https://github.com/cdfoundation/sig-interoperability/tree/master/workstreams/events_in_cicd

2021-02-04 14:03 UTC, afrittoli commented
@e-backmark-ericsson shall weinclude the link to https://github.com/cdfoundation/sig-interoperability/tree/master/workstreams/events_in_cicd in the PR? 
We could also add our ToC sponsor, @imosquera how kindly offered to be the sponsor for our SIG

2021-02-04 16:28 UTC, e-backmark-ericsson commented
@afrittoli , I don't see that we have any more valid information on that link that is not already part of this PR - The charter is here, the meetings doc is linked from the PR and the README is kind of out of date I would say when we become a SIG. Do you agree?

But of course I'll add Isaac as our appointed sponsor. I'm very glad to have you on board, @imosquera! :)

2021-02-04 16:34 UTC, afrittoli commented
Sounds good, thank you!

2021-02-23 14:04 UTC, afrittoli commented
The SIG has been approved: https://lists.cd.foundation/g/cdf-toc/message/614 🎉

2021-02-23 15:02 UTC, leefaus reviewed
Left a quick comment inline.

2021-02-23 15:02 UTC, leefaus commented on sigs/sig-events.md
> +The group is working on a standardized event protocol that caters for technology agnostic machine-to-machine communication in CI/CD systems. This specification will be published, reviewed and agreed
I'm curious to understand the need for a new *protocol*.  with a lot of companies standardizing on either grpc, httpv2 or websockets for communication between tooling do we really need something at this lower level or are you talking about having a *common schema* for events with a set of APIs inside these tools that provides communication in a standard way?  the other concern i have around implementing a *protocol* is the growing number of SaaS/Cloud offerings on the marketing, getting data in and out of tools that are deployed on-premises will require security teams to get involved in approving connectivity between disparate tools.  i ❤️  the initiative between the Interoperability SIG and the Event SIG.  Sould also be aware of other standards in this segment around [CNAB](https://cnab.io/) that purpose to do the same thing, although implemented a little differently.

2021-02-23 15:31 UTC, afrittoli commented on sigs/sig-events.md
> +The group is working on a standardized event protocol that caters for technology agnostic machine-to-machine communication in CI/CD systems. This specification will be published, reviewed and agreed
Hi @leefaus, thank you for your comment and for the link to CNAB.

Our intention is indeed to work at a higher level on the stack; we definitely do not intend to create another grpc, httpv2 or websockets. We could call the result of our work a _common schema_ instead of _protocol_; in any case it sounds like we should make sure our intentions are clear in the documentation. Our plan is - at least for cloud native platforms - is to base our work on top of [CloudEvents](https://cloudevents.io/) which includes SDKs for several programming languages, and [bindings ](https://github.com/cloudevents/spec/tree/master#cloudevents-documents) for several protocols.

2021-03-01 15:27 UTC, merged